### ISSUE TITLE
EquityTrendScreenerBot: spatne urceny context pro 3M

### ISSUE THREAD

**Issue by GeorgeQuantAnalyst** [GeorgeQuantAnalyst/trading-bots#18]
Prosim o provereni urceni 3M kontextu pro nasledujici trhy:

ScreeningDate: 7.7.2023

* EDU (Rotation -> Up-trend)
* HAL (Rotation -> Up-trend)
* LII (Rotation -> Up-trend)

**Comment by GeorgeQuantAnalyst** [comment]
## Analyza

**Podminky pro up-trend**
```python
def is_up_trend(ohlc: pd.DataFrame) -> bool:
    if ohlc.shape[0] < 4:
        return False

    two_green_candles = ohlc.loc[1]["candleColor"] == "Green" and ohlc.loc[2]["candleColor"] == "Green"
    higher_lows = ohlc.loc[0]["low"] > ohlc.loc[1]["low"] > ohlc.loc[2]["low"]
    break_high = ohlc.loc[0]["close"] > ohlc.loc[3]["high"]

    return two_green_candles and higher_lows and break_high
```

**EDU (Rotation -> Up-trend)**
- Kontext pro trh EDU nebyl urcen jako up-trend, protoze nesplnuje podminku break_high.

**HAL (Rotation -> Up-trend)**
- Splnuje podminky pro up-trend, je treba se podivat do logu na ohlc vstupni data z yfinannce.

**LII (Rotation -> Up-trend)**
- Kontext pro trh EDU nebyl urcen jako up-trend, protoze nesplnuje podminku higher_lows.

**Comment by GeorgeQuantAnalyst** [comment]
Reseni problemu vice tickeru na ruznych burzach

Pridat pred ticker zkratku burzy "NYSE" nebo "NASDAQ" v souboru obsahujici tickery a pak pri ukladani v reportu ulozit s prefixem.

```csv
Ticker
NASDAQ-AAPL
NYSE-HAL
..
```

```report
###UP-TREND, NASDAQ:APPL
```

**Comment by GeorgeQuantAnalyst** [comment]
Ceka na implementaci v ramci bug fixingu

**Comment by GeorgeQuantAnalyst** [comment]
## Code-review
TODO: @LucyQuantAnalyst

**Comment by LucyQuantAnalyst** [comment]
## Code review

OK

Zamergovano do dev vetve.
