### ISSUE TITLE
Clean code a refaktoring botu a helperu

### ISSUE THREAD

**Issue by GeorgeQuantAnalyst** [GeorgeQuantAnalyst/trading-bots#20]
Prosim o clean code a refaktoring botu a helperu, zda se mi ze se tam hodne kodu opakuje a sly by nektere metody napsat lepe.

PS: Pro code-review a navrh reseni pouzit chatGPT jako konzultanta.

Vyvoj ve vetvi: clean_code

**Comment by GeorgeQuantAnalyst** [comment]
@LucyQuantAnalyst  prosim o refaktoring tridy EquityTrendScreenerBot

**Comment by LucyQuantAnalyst** [comment]
## Code review:

@GeorgeQuantAnalyst
