### ISSUE TITLE
CryptoTrendScreenerBot: pridat do reportu sekci rotation

### ISSUE THREAD

**Issue by GeorgeQuantAnalyst** [GeorgeQuantAnalyst/trading-bots#21]
Prosim o pridani sekce "rotation" do reportu pro analytickou platformu TradingView, aby bylo mozne pote efektivne hledat break outy z range (zacatky trendu) pro obchodni strategii Breakout pullback.

**Comment by GeorgeQuantAnalyst** [comment]
## Analyza

Data jsou v ramci aplikace uz spocitane, pouze se zatim neukladaly do reportu. Jedna se o jednoduchou upravu pridani dat do reportu v metode create_tw_report() ve tride CryptoTrendScreenerBotHelper.

**Comment by GeorgeQuantAnalyst** [comment]
## Code review
TODO: @LucyQuantAnalyst

**Comment by LucyQuantAnalyst** [comment]
## Code review

OK

- zamergovano do dev vetve.
