### ISSUE TITLE
Refaktoring trading-bots

### ISSUE THREAD

**Issue by GeorgeQuantAnalyst** [GeorgeQuantAnalyst/trading-bots#30]
Prosim o refaktoring kodu v nasledujicich bodech:

* Pro nacitani dat z slozky data pouzivat repository (priklad EarlyReactionRepository)
* Cache data presunout do slozky data/cache + upravit MANIFEST.IN aby se pripojily soubory ze slozky data/cache/*
* EarlyReactionBot presunout businees logiku do helperu
* trading-bots-activity-monitor.sh nakonfigurovat pouze pro earlyReaction, placeTrailingStop crypto swing + levelTrader US stock
* Uprava unit testu dle aktualnich trid pro helpery a zprovoznit make test

Vyvoj provest do vetve: feature/app_refactoring

**Comment by LucyQuantAnalyst** [comment]
Added implementation and refactoring in this commit:

https://github.com/GeorgeQuantAnalyst/trading-bots/commit/cf31fee9217d1aafabf686d04d326db57a3e11cd
